name: lint

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Linting Dockerfile
        uses: brpaz/hadolint-action@f49a60108f34b589e16e00be852f810e8ddb2484 # master
        with:
          dockerfile: 'Dockerfile'
